### ISSUE TITLE
What is the purpose of this code?

### ISSUE THREAD

**Issue by samyakbhuta** [RahulRj09/Snake-And-Ladder-Game#10]
https://github.com/RahulRj09/Snake-And-Ladder-Game/blob/96b1d83d66f53386208b85adffd17e812902e95c/src/main/java/game/Player.java#L29

If the code has been written for debugging purpose, it is a bad practice. Should avoid it. Should use standard/idiomatic debugging practices (breakpoints, debugging tool etc!)

**Comment by RahulRj09** [comment]
Okay I will use breakpoint and debugging tool from now onwards.

**Comment by RahulRj09** [comment]
1a2d708 fixes it.

**Comment by samyakbhuta** [comment]
:+1:
