### ISSUE TITLE
Might want to add code to handle exceptional and error scenarios

### ISSUE THREAD

**Issue by samyakbhuta** [RahulRj09/Snake-And-Ladder-Game#4]
https://github.com/RahulRj09/Snake-And-Ladder-Game/blob/96b1d83d66f53386208b85adffd17e812902e95c/src/main/java/resources/pages/home.html#L11-L14

**Comment by RahulRj09** [comment]
I have done some changes. Please check it once.

**Comment by RahulRj09** [comment]
I have done some changes. Please check it once.

**Comment by RahulRj09** [comment]
34efd18 fixes it.

**Comment by samyakbhuta** [comment]
fix accepted
